language: node_js
node_js:
  - "node"
  - "6"
install:
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - dpkg -i google-chrome-stable_current_amd64.deb
  - pushd server && npm install
  - popd
  - pushd client && npm install
  - popd
  - npm install -g aurelia-cli
script:
  - pushd server && npm run all
  - popd
  - pushd client && au test
  - popd
  - pushd client && au build
  - popd
