language: node_js
node_js:
  - "node"
  - "6"
install:
  - pushd server && npm install
  - pushd client && npm install
  - npm install -g aurelia-cli
script:
  - pushd server && npm run all
  - pushd client && au test
  - pushd client && au build
